version: "3.9" ## Especifica a versão do docker-compose file

services: ## Define um servico
    database:
        image: postgres
        container_name: database_ignite
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rentalx
        volumes:
            - pgdata:/data/postgres
    app: ## Nome do servico
        build: . ## localização do dockerfile
        container_name: rentx
        restart: always
        ports:
            - "3333:3333" ## redirecionamento de porta quando chegar alguma requisição na porta 3333 chama o container na porta 3333
        volumes:
            - .:/usr/app ## monitoro a pasta atual . e envio as alterações pra /usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
